#!/bin/sh

. /etc/aodieuvps/scripts.conf

clear
prompt="Nhap vao lua chon menu cua ban:"
options=("Liet Ke Domain" "Them Domain" "Xoa Domain" "Sao Luu Code" "Sao Luu Data" "Tu Dong Sao Luu" "Tat Tu Dong Sao Luu" "Tao Database" "Xoa Database" "Doi Pass VPS" "Doi Port Admin" "Them Park Domain" "Them Redirect Domain" "Phan Quyen Webserver" "Nang Cap Server" "Doi Port SSH" "Cai SSL cho Domain" "Cai SSL cho Sub Domain" "Xoa SSL") # End Options

printf "=========================================================================\n"
printf "               AodieuVPS Script v$aodieuvps_version - http://aodieu.com/ \n"
printf "=========================================================================\n"
printf "                             AodieuVPS Menu\n"
printf "=========================================================================\n"
PS3="
$prompt"
select opt in "${options[@]}" "Thoat"; do 

    case "$REPLY" in
	    1 ) /etc/aodieuvps/menu/liet-ke-domain;;
	    2 ) /etc/aodieuvps/menu/them-domain;;
	    3 ) /etc/aodieuvps/menu/xoa-domain;;
	    4 ) /etc/aodieuvps/menu/sao-luu-code;;
	    5 ) /etc/aodieuvps/menu/sao-luu-data;;
	    6 ) /etc/aodieuvps/menu/tu-dong-sao-luu;;
	    7 ) /etc/aodieuvps/menu/tat-tu-dong-sao-luu;;
	    8 ) /etc/aodieuvps/menu/tao-database;;
	    9 ) /etc/aodieuvps/menu/xoa-database;;
	    10 ) /etc/aodieuvps/menu/doi-pass-vps;;
	    11 ) /etc/aodieuvps/menu/doi-port-admin;;
	    12 ) /etc/aodieuvps/menu/park-domain;;
	    13 ) /etc/aodieuvps/menu/forward-domain;;
	    14 ) /etc/aodieuvps/menu/phan-quyen-webserver;;
	    15 ) /etc/aodieuvps/menu/nang-cap-server;;
		16 ) /etc/aodieuvps/menu/doi-port-ssh;;
		17 ) /etc/aodieuvps/menu/cai-ssl-domain;;
		18 ) /etc/aodieuvps/menu/cai-ssl-subdomain;;
		19 ) /etc/aodieuvps/menu/xoa-ssl;;
	    # End Menu

	    $(( ${#options[@]}+1 )) ) printf "\nChao tam biet!\nHen gap lai ban o http://aodieu.com/\n\n"; break;;
	    *) echo "Ban nhap sai, vui long nhap theo so thu tu tren danh sach";continue;;

    esac

done